# generated by datamodel-codegen:
#   filename:  test.json
#   timestamp: 2021-09-10T06:28:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Model(BaseModel):
    price: Optional[float] = None
    name: Optional[str] = None
