# generated by datamodel-codegen:
#   filename:  helper/personame.json
#   timestamp: 2021-09-10T06:28:00+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class PersonName(BaseModel):
    first: str = Field(..., description='first name', title='first name')
    middle: Optional[str] = Field(None, description='middle name', title='middle name')
    last: str = Field(..., description='last name', title='last name')
