# generated by datamodel-codegen:
#   filename:  _other/_process_first_attempt.json
#   timestamp: 2021-09-10T06:28:00+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
