# generated by datamodel-codegen:
#   filename:  _other/_process.json
#   timestamp: 2021-09-10T06:28:00+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

from ..helper import time


class Label1(Enum):
    planned = 'planned'
    executed = 'executed'


class ExecutedMeta(BaseModel):
    user_id: Optional[str] = Field(
        None, description='the ID of the user', title='contributorID'
    )
    time: Optional[time.Time] = None


class Process(BaseModel):
    _id: Optional[str] = Field(
        None, alias='@id', description='unique ID for an a protocol', title='_key'
    )
    experiment: Optional[str] = Field(
        None, description='related experiment ID', title='experimentID'
    )
    label: Optional[Label1] = Field(
        None,
        description='distinction for whether it is protocol or an experiment',
        title='category',
    )
    executed_meta: Optional[ExecutedMeta] = Field(None, title='_key')
    events: Optional[List] = Field(
        None, description='id of the event', title='processID'
    )
